### ISSUE TITLE
`force-expand-multiline` doesn't work as expected

### ISSUE THREAD

**Issue by octref** [beautify-web/js-beautify#1186]
# Description

`force-expand-multiline` doesn't work as expected.

# Input
The code looked like this before beautification:
```html
<template>
  <div
    class="test"
    @click="test"
  >
    <input
      ref="test"
      v-if="test"
    >
      <div>
        <span>test</span>
      </div>
      </div>
</template>
```

# Expected Output
The code should have looked like this after beautification:
```html
<template>
  <div
    class="test"
    @click="test"
  >
    <input
      ref="test"
      v-if="test"
    >
    <div>
      <span>test</span>
    </div>
  </div>
</template>
```

# Actual Output
The  code actually looked like this after beautification:

```bash
> html-beautify --version
1.6.12
> html-beautify -f test.html -A "force-expand-multiline"
```

```html
<template>
  <div
    class="test"
    @click="test"
  >
    <input
      ref="test"
      v-if="test"
    />
      <div>
        <span>test</span>
      </div>
      </div>
</template>
```

# Steps to Reproduce

## Environment
OS: macOS 10.12.4

## Settings
```bash
> html-beautify -f test.html -A "force-expand-multiline"
```

Related https://github.com/octref/vetur/issues/99

**Comment by HADB** [comment]
+1

**Comment by bitwiseman** [comment]
@octref - your input is missing a closing /: 
```
 <input
      ref="test"
      v-if="test"
    >
```
I assume that is just a typo during bug filing.

**Comment by octref** [comment]
I thought for self closing tags `/` is optional.
But even if I add `/` this still happens.

**Comment by bitwiseman** [comment]
@octref 
You're probably right.  I don't know off the top of my head.  I mention it only because the input text was different from output (in a non-formatting way).

**Comment by octref** [comment]
@bitwiseman Right, I fixed that. Sorry for the confusion.

**Comment by msmolcic** [comment]
What's the status on this one? I'd really love to see this fixed.

**Comment by bitwiseman** [comment]
@msmolcic  - This issue is unassigned.  It needs someone to take the time to implement a fix and tests.

**Comment by GearoidCollins** [comment]
People still getting this issue?
I seem to be getting it with `"html.format.wrapAttributes": "force-expand-multiline"` on vscode@1.20.1

**Comment by Predve4niy** [comment]
it still not working on vscode@1.22.2 too

**Comment by bitwiseman** [comment]
@Predve4niy 
This issue is unassigned. It needs someone to take the time to implement a fix and tests.

**Comment by JakubKubista** [comment]
"vetur.format.defaultFormatterOptions": {
        "js-beautify-html": {
            "wrap_attributes": "force-expand-multiline",
        },
    }

Still doesn't work as expected.

**Comment by affanshahid** [comment]
+1

**Comment by EzioW** [comment]
+1

**Comment by EzioW** [comment]
@bitwiseman have you fixed it ?

**Comment by bitwiseman** [comment]
@EzioW 
This issue is unassigned. It needs someone to take the time to implement a fix and tests.
